### PR TITLE
 NetworkManager 1.2 support

### PR DESCRIPTION
**Pull request by lkundrak**
Hi Sergey,

hope you're doing well!

Please consider pulling this.

The branch contains changes that are necessary for the properties
plugin to continue working with upcoming nm-connection-editor 1.2 and
more. The details are explained in the "build: bump version to 1.1.0"
commit message.

Also, please consider branching off a "nm-1-0" branch and eventually
bumping a version to "1.0.x" there. This will make it easier for
downstream distributors of the NetworkManager up to 1.0 to track fixes
specific to the older versions.

Please note that I just did a buildcheck; I don't have a necessary
setup to test this (= I'm probably a lazy fuck). Given I've done
analogous changes to other plugins and they worked I wouldn't expect it
to be too broken or broken at all. We'll eventually test this
downstream for Fedora 24. Should you try it out and discover any
issues, please let me know.

NetworkManager 1.2 is expected to be released in around two months.

Shortlog:

Lubomir Rintel (13):
      build: properly substitute DBUS_* variables
      all: split defines off nm-l2tp-service.h
      build: bump version to 1.1.0
      build: create xz compressed tarballs by default
      build: split the plugin into two halves
      build: check for libnm & libnma
      properties: port to libnm
      properties: use the NM error types & quarks
      properties: rename the classes to be more libnm-ish
      service: port to libnm & GDBus
      auth-dialog: port to libnm
      build: allow build without libnm-glib
      build: install into /usr/lib/NetworkManager/VPN as well

Thank you,
Lubo

### CODE REVIEW

**Comment by seriyps** [comment]
Hi.
Sorry for delay and thanks for your work.

Unfortunately, I'm not yet able to properly maintain this plugin, since I don't use it myself and have not enough free time and motivation.

Of course, I may just merge this patch without any checking, but feel it'll be irresponsible.

Another problem is, AFAIK, openswan is now superseeded by strongswan, so, nm-l2tp-service should be rewritten to use new IPSec solution.

So, it will be much better, if someone else will continue plugin maintainment.

Sergey.

**Comment by ndorf** [comment]
Well, I can do at least basic maintenance if no one else wants to. I
obviously haven't had any time to do the strongswan rewrite, but I do still
intend to get to it at some point. Of course, if OP is willing to take it
over then I certainly don't object to that either :)

**Comment by lkundrak** [comment]
> Well, I can do at least basic maintenance if no one else wants to. I
obviously haven't had any time to do the strongswan rewrite, but I do still
intend to get to it at some point.

Openswan has been superceded by Libreswan. Good news is that it's not really a rewrite or anything and is still rather compatible (it could be argued that if anything works differently to the point it breaks existing setups then it's a bug).

> Of course, if OP is willing to take it over then I certainly don't object to that either :)

No, I don't really have a L2TP setup at all. However I'll be more than happy to assist if needed.

**Comment by lkundrak** [comment]
> Well, I can do at least basic maintenance if no one else wants to.

@seriyps opinions? Seems like we have a volunteer? :)

> I obviously haven't had any time to do the strongswan rewrite, but I do still intend to get to it at some point. Of course, if OP is willing to take it over then I certainly don't object to that either :)

There's a patch in my fork. I added some comments and asked the guy to carry it over to here:

https://github.com/lkundrak/NetworkManager-l2tp/pull/1

If anything, the patch seems to be a good start (though I'd welcome not breaking/removing openswan/libreswan support).

**Comment by seriyps** [comment]
@lkundrak yes, guys. If someone can continue maintainance, at least basic like "make it just work, no new features", then you are always welcome!

**Comment by lkundrak** [comment]
@seriyps, seems like @ndorf volunteered to that. I'm wondering if you could add the required permissions for him to do that?

When it comes to fixing with anything NM-related, reviewing changes, etc., I'm glad to offer a helping hand.

**Comment by seriyps** [comment]
@lkundrak @ndorf I've just added you both to collaborators of this repository. So, you are welcome!

**Pull request merged**
